### ISSUE TITLE
It's not working

### ISSUE THREAD

**Issue by aronsuarez** [bradmartin/nativescript-gradient#1]
Copy paste from NPM, wont work, only the text is displaying.

Do you have any idea?

Thanks

**Comment by bradmartin** [comment]
Had you already ran the app on a device/emulator? If so, uninstall that then remove and add the ANDROID platform back in your app and rebuild. Now run the new build. This plugin uses an android library so it needs to be downloaded and built into the app. If you didn't do a new build then the  code isn't actually in your app to do the gradient :)

**Comment by aronsuarez** [comment]
I use a ios 6 emulater. No Android. I have uninstall the  app and install again but i't wont show me gradient.

There i can say only "the ghost in the machine" :-))

**Comment by bradmartin** [comment]
This is android only right now. I have an iOS Cocoapod I might integrate,
just haven't had time for it yet.

**Comment by bradmartin** [comment]
https://github.com/bradmartin/nativescript-gradient/blob/master/README.md#native-libraries

**Comment by aronsuarez** [comment]
Sorry my fingers was faster then my eays
