### ISSUE TITLE
Can't position gradient. 

### ISSUE THREAD

**Issue by x00** [bradmartin/nativescript-gradient#2]
Is this only for page gradients? I can't seem to position. I used stack layouts, etc

I'm using Angular.

**Comment by x00** [comment]
managed to get it working with DockLayout

**Comment by bradmartin** [comment]
The `Gradient ` extends the NS `ContentView` so it works the same as the layout containers: stacklayout, grid, wrap, dock, etc. Glad you got it working and it's not just for the page, I'm sure you know that but for others to  see 😄
